services:
  product-management-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - product-management-network
    depends_on:
      - product-management-db
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=product-management-db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - SESSION_KEY=${SESSION_KEY}
      - JWT_SECRET=${JWT_SECRET}

  product-management-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data-db:/data/db
    networks:
      - product-management-network
    environment:
      - MONGO_INITDB_DATABASE=technology_shop

networks:
  product-management-network:
    driver: bridge